const fs=require('fs'),http=require('http'),{chromium}=require('playwright'),{requestHandler}=require('./browser-smoke.cjs');

(async()=>{fs.mkdirSync('qa/followup',{recursive:true});
const server=http.createServer(requestHandler);
await new Promise(ok=>server.listen(0,'127.0.0.1',ok));
let browser;
try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || require('path').resolve(__dirname,'../../toolchain/playwright/chromium-1234/chrome-linux64/chrome'),headless:true,args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1200,height:1000}});
const origin='http://127.0.0.1:'+server.address().port+'/game.html';
const seed=await context.newPage();
await seed.goto(origin);
await seed.waitForFunction(()=>Module.uplinkPersistence.ready);
await seed.evaluate(async()=>{Module.FS.writeFile('/persistent/protected-marker.txt','must-survive-restore-failure');
await Module.uplinkFlushSaves()});
const interrupted=await seed.evaluate(async()=>{Module.FS.writeFile('/persistent/recovery-marker.txt','recovered-after-abort');
window.qaTransaction=IDBDatabase.prototype.transaction;
window.qaAborts=0;
IDBDatabase.prototype.transaction=function(...args){const t=qaTransaction.apply(this,args);
if(args[1]==='readwrite'){++qaAborts;
queueMicrotask(()=>t.abort())}return t};
try{await Module.uplinkFlushSaves();
throw Error('Expected an aborted transaction')}catch(e){return {error:String(e),aborted:qaAborts,status:{...Module.uplinkPersistence}}}});
await seed.waitForTimeout(650);
await seed.screenshot({path:'qa/followup/write-aborted.png'});
const writeRecovered=await seed.evaluate(async()=>{IDBDatabase.prototype.transaction=qaTransaction;
await Module.uplinkFlushSaves();
return {...Module.uplinkPersistence}});
if(!interrupted.aborted||!interrupted.status.lastError||writeRecovered.lastError||writeRecovered.pending)throw Error('Write recovery failed');
await seed.close();
const blocked=await context.newPage();
await blocked.addInitScript(()=>{indexedDB.open=function(){throw new DOMException('QA blocked IndexedDB restore','SecurityError')}});
await blocked.goto(origin);
await blocked.waitForTimeout(6500);
const failed=await blocked.evaluate(()=>({status:Module.uplinkPersistence,calledRun:!!Module.calledRun,body:document.body.innerText.slice(0,350)}));
await blocked.screenshot({path:'qa/followup/restore-blocked.png'});
await blocked.close();
const recovered=await context.newPage();
await recovered.goto(origin);
await recovered.waitForFunction(()=>Module.uplinkPersistence.ready);
const restored=await recovered.evaluate(()=>({status:Module.uplinkPersistence,marker:Module.FS.readFile('/persistent/protected-marker.txt',{encoding:'utf8'}),recoveryMarker:Module.FS.readFile('/persistent/recovery-marker.txt',{encoding:'utf8'})}));
if(failed.status.ready||!failed.status.lastError||restored.marker!=='must-survive-restore-failure'||restored.recoveryMarker!=='recovered-after-abort')throw Error('Restore protection failed');
const result={interrupted,writeRecovered,failed,restored};
fs.writeFileSync('qa/followup/restore-results.json',JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
}finally{if(browser)await browser.close();
await new Promise(ok=>server.close(ok))}})().catch(e=>{console.error(e);
process.exitCode=1});

